### Computing PCA using RDDs

###  PCA

The vectors that we want to analyze have length, or dimension, of 365, corresponding to the number of 
days in a year.

We want to perform [Principle component analysis (PCA)](https://en.wikipedia.org/wiki/Principal_component_analysis)
on these vectors. There are two steps to this process:

1. Computing the covariance matrix: this is a  simple computation. However, it takes a long time to compute and it benefits from using an RDD because it involves all of the input vectors.
2. Computing the eigenvector decomposition. this is a more complex computation, but it takes a fraction of a second because the size to the covariance matrix is $365 \times 365$, which is quite small. We do it on the head node usin `linalg`

### Computing the covariance matrix
Suppose that the data vectors are the column vectors denoted $x$ then the covariance matrix is defined to be
$$
E(x x^T)-E(x)E(x)^T
$$

Where $x x^T$ is the **outer product** of $x$ with itself.

If the data that we have is $x_1,x_2,x_n$ then the estimates we use are:
$$
\hat{E}(x x^T) = \frac{1}{n} \sum_{i=1}^n x_i x_i^T,\;\;\;\;\;
\hat{E}(x) = \frac{1}{n} \sum_{i=1}^n x_i
$$

### `nan`s in arithmetic operations
* We store all of the measurements as single `bytearray` in a single column. Instead of using 365 columns.
* Why?
  1. Because serializing and desirializing is faster that way.
  1. Because numpy treats `nan` entries correctly:
      * In `numpy.nansum` `5+nan=5` while in dataframes `5+nan=nan`

In [1]:
import numpy as np
X=np.array([1,1,1,2])
print 'mean of',X,'=',np.mean(X)
print 'nanmean of',X,'=',np.nanmean(X)
X=np.array([1,1,np.NaN,2])
print 'mean of',X,'=',np.mean(X)
print 'nanmean of',X,'=',np.nanmean(X)

mean of [1 1 1 2] = 1.25
nanmean of [1 1 1 2] = 1.25
mean of [  1.   1.  nan   2.] = nan
nanmean of [  1.   1.  nan   2.] = 1.33333333333


#### When should you not use `np.nanmean` ?
Using `n.nanmean` is equivalent to assuming that choice of which elements to remove is independent of the values of the elements. 
* Example of bad case: suppose the larger elements have a higher probability of being `nan`. In that case `np.nanmean` will under-estimate the mean

#### Computing Cov matrix on vectors with NaNs
As it happens, we often get vectors $x$ in which some, but not all, of the entries are `nan`. 
Suppose that we want to compute the mean of the elements of $x$. If we use `np.mean` we will get the result `nan`. A useful alternative is to use `np.nanmean` which removes the `nan` elements and takes the mean of the rest.

#### Computing the covariance  when there are `nan`s
The covariance is a mean of outer products.

If the data that we have is $x_1,x_2,x_n$ then the estimates we use are:
$$
\hat{E}(x x^T) = \frac{1}{n} \sum_{i=1}^n x_i x_i^T,\;\;\;\;\;
\hat{E}(x) = \frac{1}{n} \sum_{i=1}^n x_i
$$

In [2]:
x1=np.array([1,np.NaN,3,4,5])
x2=np.array([2,3,4,np.NaN,6])
stacked=np.array([np.outer(x1,x1),np.outer(x2,x2)])
stacked

array([[[  1.,  nan,   3.,   4.,   5.],
        [ nan,  nan,  nan,  nan,  nan],
        [  3.,  nan,   9.,  12.,  15.],
        [  4.,  nan,  12.,  16.,  20.],
        [  5.,  nan,  15.,  20.,  25.]],

       [[  4.,   6.,   8.,  nan,  12.],
        [  6.,   9.,  12.,  nan,  18.],
        [  8.,  12.,  16.,  nan,  24.],
        [ nan,  nan,  nan,  nan,  nan],
        [ 12.,  18.,  24.,  nan,  36.]]])

In [3]:
np.nanmean(stacked,axis=0)

/Users/ashwinramesh/anaconda/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:703: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)


array([[  2.5,   6. ,   5.5,   4. ,   8.5],
       [  6. ,   9. ,  12. ,   nan,  18. ],
       [  5.5,  12. ,  12.5,  12. ,  19.5],
       [  4. ,   nan,  12. ,  16. ,  20. ],
       [  8.5,  18. ,  19.5,  20. ,  30.5]])

### Loading Data into Dataframe

In [4]:
import findspark
findspark.init()

from pyspark import SparkContext
#sc.stop()
## add after creating spark_PCA.py
sc = SparkContext(master="local[3]",pyFiles=['lib/numpy_pack.py','lib/computeStats.py']) #,'lib/spark_PCA.py'

from pyspark import SparkContext
from pyspark.sql import *
sqlContext = SQLContext(sc)

In [5]:
import sys
sys.path.append('./lib')

import numpy as np
from numpy_pack import packArray,unpackArray
# add after creating spark_PCA.py
# from spark_PCA import computeCov
from computeStats import computeOverAllDist, STAT_Descriptions

### Climate data

The data we will use here comes from [NOAA](https://www.ncdc.noaa.gov/). Specifically, it was downloaded from This [FTP site](ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily/).

There is a large variety of measurements from all over the world, from 1870 will 2012.
in the directory `../../Data/Weather` you will find the following useful files:

* data-source.txt: the source of the data
* ghcnd-readme.txt: A description of the content and format of the data
* ghcnd-stations.txt: A table describing the Meteorological stations.



### Data cleaning

* Most measurements exists only for a tiny fraction of the stations and years. We therefor restrict our use to the following measurements:
```python
['TMAX', 'SNOW', 'SNWD', 'TMIN', 'PRCP', 'TOBS']
```

* We consider only measurement-years that have at most 50 `NaN` entries

* We consider only measurements in the continential USA

* We partition the stations into 256 geographical rectangles, indexed from BBBBBBBB to SSSSSSSS. And each containing about 12,000 station,year pairs.

In [6]:
file_index='BBBSBBBB'
filename='US_Weather_%s.csv.gz'%file_index
data_dir='../../Data/Weather'
del_files='%s/%s*'%(data_dir,filename[:-3])
print del_files
!rm $del_files
command="curl https://mas-dse-open.s3.amazonaws.com/Weather/small/%s > %s/%s"%(filename,data_dir,filename)
print command
!$command
!ls -lh $data_dir/$filename

../../Data/Weather/US_Weather_BBBSBBBB.csv*
curl https://mas-dse-open.s3.amazonaws.com/Weather/small/US_Weather_BBBSBBBB.csv.gz > ../../Data/Weather/US_Weather_BBBSBBBB.csv.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3732k  100 3732k    0     0  3040k      0  0:00:01  0:00:01 --:--:-- 3062k
-rw-r--r--  1 ashwinramesh  staff   3.6M May  8 20:00 ../../Data/Weather/US_Weather_BBBSBBBB.csv.gz


In [7]:
!gunzip $data_dir/$filename
filename=data_dir+'/US_Weather_BBBSBBBB.csv'
!ls -lh $filename

-rw-r--r--  1 ashwinramesh  staff    13M May  8 20:00 ../../Data/Weather/US_Weather_BBBSBBBB.csv


In [8]:
import pickle
List=pickle.load(open(filename,'rb'))
len(List)

13047

In [9]:
df=sqlContext.createDataFrame(List)
print df.count()
df.show(5)

13047
+---------+--------+---------+-----------+-----------+------+--------------------+------+--------+
|elevation|latitude|longitude|measurement|    station|undefs|              vector|  year|   label|
+---------+--------+---------+-----------+-----------+------+--------------------+------+--------+
|      6.1| 42.4667|    -70.9|       TMAX|USC00198301|     0|[80 4D 00 46 E0 5...|1931.0|BBBSBBBB|
|      6.1| 42.4667|    -70.9|       TMAX|USC00198301|     0|[00 4F 80 51 00 4...|1932.0|BBBSBBBB|
|      6.1| 42.4667|    -70.9|       TMAX|USC00198301|     2|[20 D0 00 53 A0 5...|1933.0|BBBSBBBB|
|      6.1| 42.4667|    -70.9|       TMAX|USC00198301|     2|[30 55 80 C9 A0 D...|1934.0|BBBSBBBB|
|      6.1| 42.4667|    -70.9|       TMAX|USC00198301|     1|[E0 50 00 CF 00 5...|1935.0|BBBSBBBB|
+---------+--------+---------+-----------+-----------+------+--------------------+------+--------+
only showing top 5 rows



In [10]:
sqlContext.registerDataFrameAsTable(df,'weather') #using older sqlContext instead of newer (V2.0) sparkSession

In [11]:
from time import time
t=time()

N=sc.defaultParallelism
print 'Number of executors=',N
print 'took',time()-t,'seconds'

Number of executors= 3
took 0.00187683105469 seconds


### Computing PCA for each measurement

In [12]:
measurements=['TMAX', 'SNOW', 'SNWD', 'TMIN', 'PRCP', 'TOBS']

#### Homework
The code below computes the covariance matrix using RDDs.
The code allows undefined entries and calculates the covariance without bias.

Your homework is to complete the missing parts in the code (Marked with `...`) so that it would calculate the covariance correctly.

In [13]:
#%%writefile lib/spark_PCA.py #once this works correctly, you should add it to the `lib` directory
# and use import

import numpy as np
from numpy import linalg as LA

def outerProduct(X):
    """Computer outer product and indicate which locations in matrix are undefined"""
    O=np.outer(X,X)
    N=1-np.isnan(O)
    return (O,N)

def sumWithNan(M1,M2):
    """Add two pairs of (matrix,count)"""
    (X1,N1)=M1
    (X2,N2)=M2
    N=N1+N2
    X=np.nansum(np.dstack((X1,X2)),axis=2)
    return (X,N)

def computeCov(RDDin):
    """computeCov recieves as input an RDD of np arrays, all of the same length, 
    and computes the covariance matrix for that set of vectors"""
    RDD=RDDin.map(lambda v:np.array(np.insert(v,0,1),dtype=np.float64)) 
                     # insert a 1 at the beginning of each vector so that the same 
                     #calculation also yields the mean vector
    #OuterRDD=RDD ...  # separating the map and the reduce does not matter because of Spark uses lazy execution.
    #(S,N)=OuterRDD ...
    OuterRDD = RDD.map(lambda v: outerProduct(v))    #<-- do mapping here
    (S,N)= OuterRDD.reduce(lambda v1,v2: sumWithNan(v1,v2))  #<-- do reducing here
    E=S[0,1:]
    NE=np.float64(N[0,1:])
    print 'shape of E=',E.shape,'shape of NE=',NE.shape
    Mean=E/NE
    O=S[1:,1:]
    NO=np.float64(N[1:,1:])
    Cov=(O/NO) - np.outer(Mean,Mean) # This is the covariance matrix
    # Output also the diagnal which is the variance for each day
    Var=np.array([Cov[i,i] for i in range(Cov.shape[0])])
    return {'E':E,'NE':NE,'O':O,'NO':NO,'Cov':Cov,'Mean':Mean,'Var':Var}

In [15]:
from numpy import linalg as LA
STAT={}  # dictionary storing the statistics for each measurement
Clean_Tables={}

for meas in measurements:
    t=time()
    Query="SELECT * FROM weather\n\tWHERE measurement='%s' "%(meas)
    print Query
    df1 = sqlContext.sql(Query)
    data=df1.rdd.map(lambda row: unpackArray(row['vector'],np.float16))
    #get basic statistics
    STAT[meas]=computeOverAllDist(data)   # Compute the statistics 

    # compute covariance matrix
    OUT=computeCov(data)

    #find PCA decomposition
    eigval,eigvec=LA.eig(OUT['Cov'])

    # collect all of the statistics in STAT[meas]
    STAT[meas]['eigval']=eigval
    STAT[meas]['eigvec']=eigvec
    STAT[meas].update(OUT)

    print 'time for',meas,'is',time()-t

SELECT * FROM weather
	WHERE measurement='TMAX' 
shape of E= (365,) shape of NE= (365,)
time for TMAX is 21.4624090195
SELECT * FROM weather
	WHERE measurement='SNOW' 
shape of E= (365,) shape of NE= (365,)
time for SNOW is 20.5416929722
SELECT * FROM weather
	WHERE measurement='SNWD' 
shape of E= (365,) shape of NE= (365,)
time for SNWD is 12.4029290676
SELECT * FROM weather
	WHERE measurement='TMIN' 
shape of E= (365,) shape of NE= (365,)
time for TMIN is 17.5527248383
SELECT * FROM weather
	WHERE measurement='PRCP' 
shape of E= (365,) shape of NE= (365,)
time for PRCP is 26.9060628414
SELECT * FROM weather
	WHERE measurement='TOBS' 
shape of E= (365,) shape of NE= (365,)
time for TOBS is 8.64532899857


In [16]:
from pickle import dump
filename=data_dir+'/STAT_%s.pickle'%file_index
dump((STAT,STAT_Descriptions),open(filename,'wb'))
!ls -lrth $data_dir

total 264064
-rw-r--r--    1 ashwinramesh  staff   218B May  3 11:02 data-source.txt
drwxr-xr-x   10 ashwinramesh  staff   340B May  3 11:02 US_Weather_BBBSBBBB.parquet
-rw-r--r--    1 ashwinramesh  staff    16M May  3 11:02 STAT_BBBSBBBB.pickle.gz
-rw-r--r--    1 ashwinramesh  staff   2.1M May  3 11:02 stations.pkl.gz
-rw-r--r--    1 ashwinramesh  staff   270B May  3 11:02 ghcnd-version.txt
-rw-r--r--    1 ashwinramesh  staff   7.4M May  3 11:02 ghcnd-stations_buffered.txt
-rw-r--r--    1 ashwinramesh  staff   8.0M May  3 11:02 ghcnd-stations.txt
-rw-r--r--    1 ashwinramesh  staff    22K May  3 11:02 ghcnd-readme.txt
drwxr-xr-x  404 ashwinramesh  staff    13K May  3 11:02 decon_BBBSBBBB_TOBS.parquet
drwxr-xr-x  404 ashwinramesh  staff    13K May  3 11:02 decon_BBBSBBBB_SNWD.parquet
drwxr-xr-x  404 ashwinramesh  staff    13K May  3 11:02 decon_BBBSBBBB.parquet
-rw-r--r--    1 ashwinramesh  staff    13M May  8 20:00 US_Weather_BBBSBBBB.csv
-rw-r--r--    1 ashwinramesh  staff    83M May

In [24]:
print STAT['TOBS']['eigvec'][:,:1]
#['eigval']=eigval
#STAT[meas]['eigvec']=eigvec

[[ 0.03291342]
 [ 0.03416249]
 [ 0.03955753]
 [ 0.03723297]
 [ 0.03348947]
 [ 0.04161224]
 [ 0.03422484]
 [ 0.03468038]
 [ 0.03234215]
 [ 0.04223128]
 [ 0.03278021]
 [ 0.03481495]
 [ 0.0312099 ]
 [ 0.03224702]
 [ 0.03536109]
 [ 0.03962539]
 [ 0.04069203]
 [ 0.03081069]
 [ 0.02633781]
 [ 0.03879979]
 [ 0.0425846 ]
 [ 0.04476278]
 [ 0.03247582]
 [ 0.03234027]
 [ 0.03381936]
 [ 0.03335155]
 [ 0.0288168 ]
 [ 0.03610332]
 [ 0.03711944]
 [ 0.03349785]
 [ 0.04054789]
 [ 0.03586428]
 [ 0.02495968]
 [ 0.03751592]
 [ 0.03853969]
 [ 0.04359944]
 [ 0.04663326]
 [ 0.04737404]
 [ 0.04847001]
 [ 0.05379039]
 [ 0.04200549]
 [ 0.04171563]
 [ 0.04413544]
 [ 0.0468801 ]
 [ 0.04832172]
 [ 0.05071174]
 [ 0.04393667]
 [ 0.04594786]
 [ 0.04746098]
 [ 0.045853  ]
 [ 0.04587298]
 [ 0.03996165]
 [ 0.04431091]
 [ 0.03842366]
 [ 0.05000713]
 [ 0.04859832]
 [ 0.05114412]
 [ 0.050204  ]
 [ 0.04431391]
 [ 0.04746217]
 [ 0.04739343]
 [ 0.04699185]
 [ 0.0457097 ]
 [ 0.04228392]
 [ 0.04428402]
 [ 0.03489799]
 [ 0.03606